// Package refstore persists reference records in a SQLite database: name
// bytes → CBOR record bytes, stored verbatim. It is a dumb KV layer; record
// validation belongs to the daemon and the reference package.
//
// The database is <dir>/refs.sqlite in WAL mode, so any number of processes
// may hold a store open at once: readers work from a snapshot and never
// block, and writers — in this process or another — queue behind one another
// (SQLite runs one write transaction at a time; a second writer waits up to
// busyTimeout). The file format is shared with other implementations; see
// architecture/references.md. Queries are generated by sqlc from queries.sql,
// and the schema is built by the numbered files in migrations/.
package refstore

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/draganm/rebma/refstore/internal/refsdb"
)

// ErrNotFound is returned by Get, Delete and the compare forms for an absent name.
var ErrNotFound = errors.New("refstore: reference not found")

// Store is a SQLite-backed name→record map. It is safe for concurrent use,
// by goroutines and by processes. Readers (Get, All) never block; writes are
// serialized in-process by writeMu, so they queue on the mutex rather than
// polling SQLite's file lock, and across processes by SQLite itself.
type Store struct {
	db         *sql.DB
	q          *refsdb.Queries
	writeMu    sync.Mutex
	syncWrites bool // Open's sync flag: whether a commit is fsynced
}

// Open opens (creating if missing) the refs database in dir. sync selects
// the write durability, matching the daemon's --sync flag. A Pebble store
// left in dir by an earlier release is imported first; see migrate.go.
func Open(dir string, sync bool) (*Store, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("refstore: creating %s: %w", dir, err)
	}
	if err := migrateLegacy(dir); err != nil {
		return nil, err
	}
	db, err := openDB(filepath.Join(dir, dbFile), sync, true)
	if err != nil {
		return nil, err
	}
	return &Store{db: db, q: refsdb.New(db), syncWrites: sync}, nil
}

// Put stores record under name, overwriting unconditionally.
func (s *Store) Put(name string, record []byte) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	return s.q.PutRecord(context.Background(), refsdb.PutRecordParams{Name: blob([]byte(name)), Record: blob(record)})
}

// PutBatch publishes records atomically, using the configured write durability.
// When names repeat, the last record wins. An empty batch changes nothing.
func (s *Store) PutBatch(records []Record) (err error) {
	if len(records) == 0 {
		return nil
	}
	ctx := context.Background()
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	// Unconditional, and a no-op once committed: a panic must not leave the
	// write lock held, which would wedge every writer in every process.
	defer tx.Rollback()
	q := s.q.WithTx(tx)
	for _, r := range records {
		if err = q.PutRecord(ctx, refsdb.PutRecordParams{Name: blob([]byte(r.Name)), Record: blob(r.Data)}); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// Get returns the record stored under name, or ErrNotFound.
func (s *Store) Get(name string) ([]byte, error) {
	record, err := s.q.GetRecord(context.Background(), blob([]byte(name)))
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return blob(record), nil
}

// Delete removes name, or returns ErrNotFound if absent. The check is the
// statement's own row count, so concurrent Deletes of the same name — from
// any process — report ErrNotFound to all but one caller.
func (s *Store) Delete(name string) error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	n, err := s.q.DeleteRecord(context.Background(), blob([]byte(name)))
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// Record is one (name, record-bytes) pair from All.
type Record struct {
	Name string
	Data []byte
}

// All returns every record in lexicographic name order, from one snapshot.
func (s *Store) All() ([]Record, error) {
	rows, err := s.q.ListRecords(context.Background())
	if err != nil {
		return nil, err
	}
	recs := make([]Record, len(rows))
	for i, r := range rows {
		recs[i] = Record{Name: string(r.Name), Data: blob(r.Record)}
	}
	return recs, nil
}

// Wipe deletes every record (the store-wipe operation).
func (s *Store) Wipe() error {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()
	return s.q.DeleteAllRecords(context.Background())
}

// Close closes the database.
func (s *Store) Close() error {
	return s.db.Close()
}
